# Generated by Django 4.1.7 on 2023-05-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('idAdministrativo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('cargo', models.CharField(max_length=80)),
                ('documento', models.CharField(max_length=20)),
                ('codigo', models.IntegerField()),
            ],
            options={
                'db_table': 'Administrativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Denegado', 'Denegado'), ('En proceso', 'Progreso')], default='En proceso', max_length=15)),
                ('correcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'evento',
                'managed': False,
            },
        ),
    ]
