# Generated by Django 4.1.7 on 2023-05-01 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('user', '0008_remove_estudiante_id_estudiante_idestudiante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('idActividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=150)),
                ('lugar', models.CharField(max_length=50)),
                ('estado', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsistenciaActividad',
            fields=[
                ('idAsistencia', models.AutoField(primary_key=True, serialize=False)),
                ('horas_registradas', models.IntegerField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'asistenciaactividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsistenciaEvento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horas_registradas', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('estudiante', models.ForeignKey(db_column='Estudiante_idEstudiante', on_delete=django.db.models.deletion.CASCADE, to='user.estudiante')),
                ('evento', models.ForeignKey(db_column='Evento_idEvento', on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
            ],
        ),
    ]
