# Generated by Django 4.1.7 on 2023-05-01 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horasregistradas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistenciaevento',
            name='estudiante',
        ),
    ]
