# Generated by Django 4.1.7 on 2023-04-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='Rol_idRole',
            new_name='Rol_idRol',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='idEstudiante',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='idPerfil',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='idPrograma',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='idRol',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='id_estudiante',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='id_perfil',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='programa',
            name='id_programa',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='id_rol',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
