# Generated by Django 4.1.7 on 2023-04-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_rol_idrole_perfil_rol_idrol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='id_estudiante',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='id_perfil',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='programa',
            name='id_programa',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rol',
            name='id_rol',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
