# Generated by Django 4.1.7 on 2023-04-19 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_estudiante_id_estudiante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='Perfil_idPerfil',
            new_name='id_perfil',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='Programa_idPrograma',
            new_name='id_programa',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='Rol_idRol',
            new_name='id_rol',
        ),
    ]
