# Generated by Django 4.1.7 on 2023-04-19 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_perfil_idperfil_estudiante_id_perfil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='id_perfil',
            new_name='perfil',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='id_programa',
            new_name='programa',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='id_rol',
            new_name='rol',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='id_estudiante',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='id_perfil',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='id_programa',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='id_rol',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programa',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programa',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rol',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rol',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
