# Generated by Django 4.1.7 on 2023-04-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_id_perfil_estudiante_perfil_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'managed': False},
        ),
    ]
