# Generated by Django 4.1.7 on 2023-04-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_perfil_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='perfil',
            table='perfil',
        ),
    ]
