# Generated by Django 4.1.7 on 2023-05-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_rol_options_alter_perfil_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='id',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='idEstudiante',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
    ]
