# Generated by Django 4.1.7 on 2023-04-11 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idPerfil', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=80)),
                ('correo', models.CharField(max_length=80)),
                ('contrasena', models.CharField(max_length=80)),
                ('tipo_documento', models.CharField(max_length=45)),
                ('documento', models.CharField(max_length=20)),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('idPerfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.perfil')),
            ],
        ),
    ]
